server:
  port: 18085
spring:
  application:
    name: tracing

otel:
  exporter:
    otlp:
      endpoint:
      compression: gzip
      protocol: grpc
  logs:
    exporter: none
  resource:
    attributes:
      service.name: test
  instrumentation:
    micrometer:
      enabled: true